services:
  db:
    image: postgres:17-alpine
    container_name: go_ecommerce_aug69
    restart: always
    environment:
      POSTGRES_USER: gp
      POSTGRES_PASSWORD: gp
      POSTGRES_DB: go_ecommerce_aug69
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: